$(document).ready(function(){
	$("#form_cotizacion").validate({
		rules:{
			cotizacion:"required",
			empresa:"required",
			total:"required",
			datepicker:"required"
		},
		messages:{
			cotizacion:"",
			empresa:"",
			total:"",
			datepicker:""
		}
	});
});