$(document).ready(function(){
	var contador1=1;
	var contador2=1;
	var contador3=1;
	var contador4=1;
	var contador5=1;
	var contador6=1;
	/*$("#inicio").click(function(){
		if(contador1==0){
			$("#submenu1").children("#children1").slideUp();
			contador1=1;
		}
		if(contador2==0){
			$("#submenu2").children("#children2").slideUp();
			contador2=1;
		}
		if(contador3==0){
			$("#submenu3").children("#children3").slideUp();
			contador3=1;
		}
	});*/
	$("#submenu1").click(function(){
		if(contador1==1){
			$(this).children("#children1").slideDown();
			contador1=0;
		}else{
			contador1=1;
			$(this).children("#children1").slideUp();
		}
		if(contador2==0){
			$("#submenu2").children("#children2").slideUp();
			contador2=1;
		}
		if(contador3==0){
			$("#submenu3").children("#children3").slideUp();
			contador3=1;
		}
		if(contador4==0){
			$("#submenu4").children("#children4").slideUp();
			contador4=1;
		}
		if(contador5==0){
			$("#submenu5").children("#children5").slideUp();
			contador5=1;
		}
		if(contador6==0){
			$("#submenu6").children("#children6").slideUp();
			contador6=1;
		}
	});
	$("#submenu2").click(function(){
		if(contador2==1){
			$(this).children("#children2").slideDown();
			contador2=0;
		}else{
			contador2=1;
			$(this).children("#children2").slideUp();
		}
		if(contador1==0){
			$("#submenu1").children("#children1").slideUp();
			contador1=1;
		}
		if(contador3==0){
			$("#submenu3").children("#children3").slideUp();
			contador3=1;
		}
		if(contador4==0){
			$("#submenu4").children("#children4").slideUp();
			contador4=1;
		}
		if(contador5==0){
			$("#submenu5").children("#children5").slideUp();
			contador5=1;
		}
		if(contador6==0){
			$("#submenu6").children("#children6").slideUp();
			contador6=1;
		}
	});
	/*$("#matricula").click(function(){
		if(contador1==0){
			$("#submenu1").children("#children1").slideUp();
			contador1=1;
		}
		if(contador2==0){
			$("#submenu2").children("#children2").slideUp();
			contador2=1;
		}
		if(contador3==0){
			$("#submenu3").children("#children3").slideUp();
			contador3=1;
		}
	});*/
	$("#submenu3").click(function(){
		if(contador3==1){
			$(this).children("#children3").slideDown();
			contador3=0;
		}else{
			contador3=1;
			$(this).children("#children3").slideUp();
		}
		if(contador1==0){
			$("#submenu1").children("#children1").slideUp();
			contador1=1;
		}
		if(contador2==0){
			$("#submenu2").children("#children2").slideUp();
			contador2=1;
		}
		if(contador4==0){
			$("#submenu4").children("#children4").slideUp();
			contador4=1;
		}
		if(contador5==0){
			$("#submenu5").children("#children5").slideUp();
			contador5=1;
		}
		if(contador6==0){
			$("#submenu6").children("#children6").slideUp();
			contador6=1;
		}
	});
	$("#submenu4").click(function(){
		if(contador4==1){
			$(this).children("#children4").slideDown();
			contador4=0;
		}else{
			contador4=1;
			$(this).children("#children4").slideUp();
		}
		if(contador1==0){
			$("#submenu1").children("#children1").slideUp();
			contador1=1;
		}
		if(contador2==0){
			$("#submenu2").children("#children2").slideUp();
			contador2=1;
		}
		if(contador3==0){
			$("#submenu3").children("#children3").slideUp();
			contador3=1;
		}
		if(contador5==0){
			$("#submenu5").children("#children5").slideUp();
			contador5=1;
		}
		if(contador6==0){
			$("#submenu6").children("#children6").slideUp();
			contador6=1;
		}
	});
	$("#submenu5").click(function(){
		if(contador5==1){
			$(this).children("#children5").slideDown();
			contador5=0;
		}else{
			contador5=1;
			$(this).children("#children5").slideUp();
		}
		if(contador1==0){
			$("#submenu1").children("#children1").slideUp();
			contador1=1;
		}
		if(contador2==0){
			$("#submenu2").children("#children2").slideUp();
			contador2=1;
		}
		if(contador3==0){
			$("#submenu3").children("#children3").slideUp();
			contador3=1;
		}
		if(contador4==0){
			$("#submenu4").children("#children4").slideUp();
			contador4=1;
		}
		if(contador6==0){
			$("#submenu6").children("#children6").slideUp();
			contador6=1;
		}
	});$("#submenu6").click(function(){
		if(contador6==1){
			$(this).children("#children6").slideDown();
			contador6=0;
		}else{
			contador5=1;
			$(this).children("#children5").slideUp();
		}
		if(contador1==0){
			$("#submenu1").children("#children1").slideUp();
			contador1=1;
		}
		if(contador2==0){
			$("#submenu2").children("#children2").slideUp();
			contador2=1;
		}
		if(contador3==0){
			$("#submenu3").children("#children3").slideUp();
			contador3=1;
		}
		if(contador4==0){
			$("#submenu4").children("#children4").slideUp();
			contador4=1;
		}
		if(contador5==0){
			$("#submenu5").children("#children5").slideUp();
			contador5=1;
		}
	});
	/*$("#cerrar").click(function(){
		if(contador1==0){
			$("#submenu1").children("#children1").slideUp();
			contador1=1;
		}
		if(contador2==0){
			$("#submenu2").children("#children2").slideUp();
			contador2=1;
		}
		if(contador3==0){
			$("#submenu3").children("#children3").slideUp();
			contador3=1;
		}
	});*/
});